@startuml

class Mapa {
  - origen: PasarelaLargada
  - meta: PasarelaMeta
  - parcelas: List<Parcela>
}


abstract class Parcela {
  - coordenada: Coordenada
  - mapa: Mapa
  - construible: Construible
  -  movible : Movible

}

interface Defensa {
  - nombre: string
  - puntosDefensa: int
  - costo: int
}

class Jugador {
- creditos: Creditos
  - nombre: String
  - defensas: List<ParcelaDeTierra>
  - estadoDeVida: EstadoVida
}

interface Enemigo {

}

class AlgoDefense {
  - mapa: Mapa
  - jugador: Jugador
  - enemigos: List<Enemigo>
  - turnoActual: int
  - enemigosPorTurno: Map<Integer, List<Enemigo>>

}

Jugador *--AlgoDefense
Mapa *--AlgoDefense
Parcela *--Mapa
Enemigo o--AlgoDefense
Defensa o--Jugador




@enduml
