@startuml
participant Actor
Actor -> AlgoDefense : ataqueJugador
activate AlgoDefense
AlgoDefense -> Jugador : atacarEnemigos
activate Jugador
Jugador -> ParcelaDeTierra : atacar
activate ParcelaDeTierra
ParcelaDeTierra -> Defensa : atacar
activate Defensa
Defensa --> ParcelaDeTierra
deactivate Defensa
ParcelaDeTierra --> Jugador
deactivate ParcelaDeTierra
Jugador -> Enemigo : recolectarCreditos
activate Enemigo
Enemigo --> Jugador
deactivate Enemigo
Jugador -> Creditos : agregarCreditos
activate Creditos
Creditos --> Jugador
deactivate Creditos
Jugador --> AlgoDefense
deactivate Jugador
return
@enduml