@startuml
participant Actor
Actor -> VoladorEnL : moverse
activate VoladorEnL
VoladorEnL -> VoladorEnL : volarEnL
activate VoladorEnL
VoladorEnL -> VoladorEnL : getPasarelaActual
activate VoladorEnL
VoladorEnL --> VoladorEnL
deactivate VoladorEnL
VoladorEnL -> Parcela : getCoordenada
activate Parcela
Parcela --> VoladorEnL
deactivate Parcela
VoladorEnL -> Coordenada : getAbscisa
activate Coordenada
Coordenada --> VoladorEnL
deactivate Coordenada
VoladorEnL -> VoladorEnL : getPasarelaActual
activate VoladorEnL
VoladorEnL --> VoladorEnL
deactivate VoladorEnL
VoladorEnL -> Parcela : getCoordenada
activate Parcela
Parcela --> VoladorEnL
deactivate Parcela
VoladorEnL -> Coordenada : getOrdenada
activate Coordenada
Coordenada --> VoladorEnL
deactivate Coordenada
VoladorEnL -> Mapa : getMeta
activate Mapa
Mapa --> VoladorEnL
deactivate Mapa
VoladorEnL -> Parcela : getCoordenada
activate Parcela
Parcela --> VoladorEnL
deactivate Parcela
VoladorEnL -> Coordenada : getAbscisa
activate Coordenada
Coordenada --> VoladorEnL
deactivate Coordenada
VoladorEnL -> Mapa : getMeta
activate Mapa
Mapa --> VoladorEnL
deactivate Mapa
VoladorEnL -> Parcela : getCoordenada
activate Parcela
Parcela --> VoladorEnL
deactivate Parcela
VoladorEnL -> Coordenada : getOrdenada
activate Coordenada
Coordenada --> VoladorEnL
deactivate Coordenada
VoladorEnL -> Mapa : obtenerParcelaConCoordenadas
activate Mapa
create Coordenada
Mapa -> Coordenada : new
activate Coordenada
Coordenada --> Mapa
deactivate Coordenada
Mapa -> Mapa : getParcelas
activate Mapa
Mapa --> Mapa
deactivate Mapa
Mapa -> Parcela : getCoordenada
activate Parcela
Parcela --> Mapa
deactivate Parcela
Mapa -> Coordenada : equals
activate Coordenada
Coordenada -> Object : getClass
activate Object
Object --> Coordenada
deactivate Object
Coordenada -> Object : getClass
activate Object
Object --> Coordenada
deactivate Object
Coordenada --> Mapa
deactivate Coordenada
Mapa --> VoladorEnL
deactivate Mapa
VoladorEnL --> VoladorEnL
deactivate VoladorEnL
VoladorEnL -> VoladorEnL : setPasarelaActual
activate VoladorEnL
VoladorEnL --> VoladorEnL
deactivate VoladorEnL
return
@enduml